sudo: required
dist: trusty
language: ruby
bundler_args: --without benchmarks development
# Pin Rubygems to a working version. Sometimes it breaks upstream. Update now and then.
before_install:
  - gem --version
  - gem update --system 2.6.7
  - gem update bundler
  - gem --version
  - bash .travis_setup.sh
addons:
  hosts:
    - mysql2gem.example.com
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
rvm:
  - 2.4
  - 2.3.1
  - ruby-head
matrix:
  include:
    - rvm: 2.3.1
      env: DB=mysql57
      addons:
        hosts:
          - mysql2gem.example.com
    - rvm: 2.3.1
      env: DB=mysql80
      addons:
        hosts:
          - mysql2gem.example.com
    - rvm: 2.3.1
      env: DB=mysql56
      os: osx
      addons:
        hosts:
          - mysql2gem.example.com
  fast_finish: true
